[env:esp32dev]
platform = espressif32@6.7.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
; upload_port = /dev/ttyUSB0  ; Uncomment and set for your system
build_flags =
  -DAUTOFUZZER_VERSION=\"4.0\"
lib_deps =
  adafruit/Adafruit SSD1306 @ ^2.5.9
  adafruit/Adafruit GFX Library @ ^1.11.9
